pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        // 讯飞 aar 通过 app/libs 引用；这行是保险用的
        flatDir { dirs("${rootDir}/app/libs") }
    }
}
rootProject.name = "DailyHealth"
include ':app'
